### ISSUE TITLE
当有多个局域网IP时，二维码页面会不停跳动

### ISSUE THREAD

**Issue by maplefz** [williamnie/netSend#4]
因为安装了虚拟机，有多个局域网IP，传输文件界面二维码页面会一直不停跳动
![2022-02-15 21-26-49](https://user-images.githubusercontent.com/3821815/154071575-8cc6e152-66ac-4bfe-9616-d9785f75e1d1.gif)

**Comment by williamnie** [comment]
感觉像是样式问题，我晚上处理下

**Comment by williamnie** [comment]
https://github.com/williamnie/netSend/releases/tag/v1.1.3
这个版本修复了，可以下载试一下

**Comment by maplefz** [comment]
可以了，没问题
