### ISSUE TITLE
建议增加UI交互效果

### ISSUE THREAD

**Issue by chenchaohan** [williamnie/netSend#6]
在电脑上安装好了 netSend 后， 拖进去一本书，上面提示点击复制地址， 点击了一点反应都没有，我还以为没成功呢！！！！
建议增加点复制成功的效果呀！

**Comment by williamnie** [comment]
嗯，正在重构中，准备支持一些新的功能，会加进去

**Comment by williamnie** [comment]
已经增加了交互效果，可以下载2.0版本尝试下 @chenchaohan
