### ISSUE TITLE
win11 安装后不正常

### ISSUE THREAD

**Issue by xy464193** [williamnie/netSend#9]
在小众软件LANDrop页面，看到你自己发的连接，然后去下载安装后，软件能正常打开，把软件里面拖拽文件没反应，点击ip后，默认浏览器打开的地址http://127.0.0.1/help，显示“无法访问此网站”
![1](https://user-images.githubusercontent.com/80197427/224463525-a984d07e-1bf2-4e33-a855-774ae385faac.png)

**Comment by williamnie** [comment]
> 在小众软件LANDrop页面，看到你自己发的连接，然后去下载安装后，软件能正常打开，把软件里面拖拽文件没反应，点击ip后，默认浏览器打开的地址[http://127.0.0.1/help，显示“无法访问此网站”](http://127.0.0.1/help%EF%BC%8C%E6%98%BE%E7%A4%BA%E2%80%9C%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE%E6%AD%A4%E7%BD%91%E7%AB%99%E2%80%9D) ![1](https://user-images.githubusercontent.com/80197427/224463525-a984d07e-1bf2-4e33-a855-774ae385faac.png)

看样子像是本地网络环境问题，help页面是供手机文件上传到电脑用的。直接把文件拖到程序页面，没任何反应么？

**Comment by xy464193** [comment]
> > [landrop页面，看到看到自己的连接，然后自己发，然后下载安装，](http://127.0.0.1/help%EF%BC%8C%E6%98%BE%E7%A4%BA%E2%80%9C%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE%E6%AD%A4%E7%BD%91%E7%AB%99%E2%80%9D)软件下载，软件软件，把能正常，把能，把把软件软件里面里面里面[.0.1/help，显示“无法访问此网站”](http://127.0.0.1/help%EF%BC%8C%E6%98%BE%E7%A4%BA%E2%80%9C%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE%E6%AD%A4%E7%BD%91%E7%AB%99%E2%80%9D) ![1个](https://user-images.githubusercontent.com/80197427/224463525-a984d07e-1bf2-4e33-a855-774ae385faac.png)
> 
> 看样子像是本地网络环境问题，帮助页面是提供手机文件上传到电脑的。直接把文件拖到程序页面，没有什么反应呢？

对的，文件拖到程序，没任何反应！

**Comment by williamnie** [comment]
> > > [landrop页面，看到看到自己的连接，然后自己发，然后下载安装，](http://127.0.0.1/help%EF%BC%8C%E6%98%BE%E7%A4%BA%E2%80%9C%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE%E6%AD%A4%E7%BD%91%E7%AB%99%E2%80%9D)软件下载，软件软件，把能正常，把能，把把软件软件里面里面里面[.0.1/help，显示“无法访问此网站”](http://127.0.0.1/help%EF%BC%8C%E6%98%BE%E7%A4%BA%E2%80%9C%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE%E6%AD%A4%E7%BD%91%E7%AB%99%E2%80%9D) ![1个](https://user-images.githubusercontent.com/80197427/224463525-a984d07e-1bf2-4e33-a855-774ae385faac.png)
> > 
> > 
> > 看样子像是本地网络环境问题，帮助页面是提供手机文件上传到电脑的。直接把文件拖到程序页面，没有什么反应呢？
> 
> 对的，文件拖到程序，没任何反应！

尝试下使用管理员权限打开下试试，感觉是读取文件缺少权限，你本地的网络环境是啥样的，挂着vpn么？内网怎么是10.0开头的

**Comment by williamnie** [comment]
@xy464193 可以给我邮箱（yebeixiaohai@gmail.com）发个联系方式么？可以远程看看是哪里的问题，

**Comment by xy464193** [comment]
> > > > [landrop页面，看到看到自己的连接，然后自己发，然后下载安装，](http://127.0.0.1/help%EF%BC%8C%E6%98%BE%E7%A4%BA%E2%80%9C%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE%E6%AD%A4%E7%BD%91%E7%AB%99%E2%80%9D)软件下载，软件软件，把能正常，把能，把把软件软件里面里面里面[.0.1/help，显示“无法访问此网站”](http://127.0.0.1/help%EF%BC%8C%E6%98%BE%E7%A4%BA%E2%80%9C%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE%E6%AD%A4%E7%BD%91%E7%AB%99%E2%80%9D) ![1个](https://user-images.githubusercontent.com/80197427/224463525-a984d07e-1bf2-4e33-a855-774ae385faac.png)
> > > 
> > > 
> > > 看样子像是本地网络环境问题，帮助页面是提供手机文件上传到电脑的。直接把文件拖到程序页面，没有什么反应呢？
> > 
> > 
> > 对的，文件拖到程序，没任何反应！
> 
> 尝试下使用管理员权限打开下试试，感觉是读取文件缺少权限，你本地的网络环境是啥样的，挂着vpn么？内网怎么是10.0开头的

我使用管理员模式打开过，往里不能拖文件进去！我是路由器配置的A类地址，所以你看到的是10.0.0.x的ip地址。

**Comment by williamnie** [comment]
已修复：https://github.com/williamnie/netSend/releases/tag/v2.0.5.5
